added shorter processing to get IPs with old version as backup

diff --git a/get-ip b/get-ip
--- a/get-ip
+++ b/get-ip
@@ -1,40 +1,46 @@
 #!/bin/bash
 # author: Mike Rodarte
 # accepts single command line argument of all
-# example usage: ./get-ip all
-#                ./get-ip
+# example usage: ./get-ip
 
-file="ipaddr"
-touch ${file}
-ip addr > ${file}
-i=0
-found=false
-ips=()
-while read line
-do
+ifconfig | grep "inet addr" | awk -F: '{ print $2 }' | awk '{ print $1 }' 
+
+# get return code from command
+rc=$?
+# if command failed, do it the old fashioned way
+if [ "${rc}" -gt 0 ]; then
+  file="ipaddr"
+  touch ${file}
+  ip addr > ${file}
+  i=0
+  found=false
+  ips=()
+  while read line
+  do
     if [[ "$i" -eq "2" ]]; then
         # http://stackoverflow.com/questions/13373249/extract-substring-using-regexp-in-plain-bash
-        ip=$([[ "$line" =~ ([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}) ]] && echo ${BASH_REMATCH[1]})
-        ips+=($ip)
+      ip=$([[ "$line" =~ ([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}) ]] && echo ${BASH_REMATCH[1]})
+      ips+=($ip)
     fi
 
     if echo "$line" | grep -q "BROADCAST"; then
-        found=true
-        i=0
+      found=true
+      i=0
     fi
 
     if $found; then
-        i=$(($i + 1))
+      i=$(($i + 1))
     fi
-done < $file
+  done < $file
 
-if [[ "$1" = "all" ]]; then
+  if [[ "$1" = "all" ]]; then
     for var in "${ips[@]}"
     do
-        echo "${var}"
+      echo "${var}"
     done
-else
+  else
     echo "${ips[0]}"
-fi
+  fi
 
-rm -f $file
+  rm -f $file
+fi
